from datetime import datetime
from ..latex_base import e, score_cmd

def cover_page(title: str, entries: list, date_str: str) -> str:
    n_scenarios = len(entries)
    
    # Calculate aggregate metrics
    total_episodes = sum(entry["agg"].get("total", 0) for entry in entries)
    avg_p1_quality = sum(entry.get("p1_score", 0) for entry in entries) / max(n_scenarios, 1)
    
    # Solve rate is (sum of solved episodes) / (sum of total episodes)
    total_solved = sum(entry["agg"].get("solved", 0) for entry in entries)
    overall_solve_rate = (total_solved / max(total_episodes, 1)) * 100

    return rf"""
\begin{{titlepage}}
\centering
\vspace*{{2cm}}
{{\Huge\bfseries\color{{titleblue}} {e(title)} \par}}
\vspace{{0.5cm}}
{{\Large\bfseries Automated Scenario Generation \& Evaluation --- MSc Research \par}}
\vspace{{1cm}}
{{\large Generated: {date_str} \par}}
\vspace{{2.5cm}}

\begin{{multicols}}{{4}}
  \kpibox{{{n_scenarios}}}{{Scenario Configs}}
  \kpibox{{{total_episodes}}}{{Total Episodes}}
  \kpibox{{{avg_p1_quality:.1f}/10}}{{Avg P1 Quality}}
  \kpibox{{{overall_solve_rate:.0f}\%}}{{Overall Solve Rate}}
\end{{multicols}}

\vspace{{2cm}}
\begin{{minipage}}{{0.85\textwidth}}
\noindent\large
This report summarises {n_scenarios} domain configuration(s) generated by the CyberBattleSim 
Domain Generator pipeline and evaluated with BFS planner-agent runtime tests. 
Each scenario represents a distinct enterprise network topology with realistic 
vulnerability chains derived from real-world CVE data.
\end{{minipage}}

\vfill
{{\large Generated by CyberBattleSim Domain Generator Pipeline \par}}
\end{{titlepage}}
"""

def overview_table(entries: list) -> str:
    rows = []
    for entry in entries:
        sr = entry["agg"].get("solve_rate", 0)
        sr_pct = f"{sr*100:.1f}\%"
        rows.append(f"  {e(entry['short_name'])} & {e(entry['arch_type'])} & "
                    f"{score_cmd(entry['p1_score'], entry['p1_grade'])} & {sr_pct} \\\\")
    
    rows_str = "\n".join(rows)
    return rf"""
\section{{Dataset Overview}}
\begin{{tabularx}}{{\textwidth}}{{lXrr}}
\toprule
\textbf{{Scenario}} & \textbf{{Architecture}} & \textbf{{Phase 1 Quality}} & \textbf{{Solve Rate}} \\
\midrule
{rows_str}
\bottomrule
\end{{tabularx}}
"""
