"""
tools/trivy_to_config.py
========================
Converts Trivy scan results + repo analysis into a rich intelligence prompt
that the LLM uses to generate a grounded CyberBattleSim domain config YAML.

Rather than generating the YAML directly (brittle), this module produces:
  1. A structured intelligence report (CVEs, tech stack, attack surface)
  2. A formatted prompt string ready for generate_template_yaml
  3. Seed snippets for solvability_vulnerabilities (for the LLM to refine)

Usage (standalone):
    python tools/trivy_to_config.py \\
        --scan scan.json \\
        --analysis analysis.json \\
        --description "Web app with AD backend" \\
        --out prompt.txt
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ── Pre-built dataset loader ──────────────────────────────────────────────────

_VULN_DB_DIR = Path(__file__).resolve().parent.parent / "data" / "vulnerability_db"
_BITNAMI_CVE_PATH     = _VULN_DB_DIR / "bitnami_cves.json"
_BITNAMI_CHART_PATH   = _VULN_DB_DIR / "bitnami_chart_analysis.json"


def load_bitnami_dataset() -> tuple[dict, dict]:
    """
    Load the pre-built Bitnami CVE dataset and chart analysis from
    data/vulnerability_db/.  Returns (scan_data, analysis_data).
    Both files are generated by running:
        tools/trivy_scanner.py  (image scans)
        tools/repo_analyzer.py  (chart structure)
    """
    scan_data: dict = {"top_cves": [], "cve_count": 0, "critical": 0, "high": 0,
                       "network_exploitable": 0, "pkg_managers": ["helm"]}
    analysis_data: dict = {"helm_charts": [], "all_properties": [], "tiers": {},
                           "service_map": {}, "subprojects": [], "docker_services": []}

    if _BITNAMI_CVE_PATH.exists():
        raw = json.loads(_BITNAMI_CVE_PATH.read_text())
        cves = raw.get("cves", [])
        scan_data = {
            "repo_url":            "https://github.com/bitnami/charts",
            "cve_count":           len(cves),
            "critical":            sum(1 for c in cves if c.get("severity") == "CRITICAL"),
            "high":                sum(1 for c in cves if c.get("severity") == "HIGH"),
            "network_exploitable": sum(1 for c in cves if c.get("attack_vector") == "NETWORK"),
            "pkg_managers":        raw.get("charts_scanned", []),
            "top_cves":            sorted(cves, key=lambda c: c.get("cvss_score", 0), reverse=True)[:30],
        }

    if _BITNAMI_CHART_PATH.exists():
        analysis_data = json.loads(_BITNAMI_CHART_PATH.read_text())

    return scan_data, analysis_data


def filter_dataset_for_charts(
    scan_data: dict,
    analysis_data: dict,
    chart_names: List[str],
) -> tuple[dict, dict]:
    """
    Filter the full Bitnami dataset to only CVEs and charts matching the
    requested subset (e.g. ['postgresql', 'redis', 'nginx']).
    """
    name_set = {n.lower() for n in chart_names}

    filtered_cves = [
        c for c in scan_data.get("top_cves", [])
        if c.get("chart", "").lower() in name_set
    ]
    filtered_charts = [
        hc for hc in analysis_data.get("helm_charts", [])
        if hc.get("name", "").lower() in name_set
    ]

    all_props = sorted({p for hc in filtered_charts for p in hc.get("properties", [])})

    filtered_scan = {**scan_data,
                     "top_cves": sorted(filtered_cves, key=lambda c: c.get("cvss_score", 0), reverse=True),
                     "cve_count": len(filtered_cves)}
    filtered_analysis = {**analysis_data,
                         "helm_charts": filtered_charts,
                         "all_properties": all_props}
    return filtered_scan, filtered_analysis


# ── CVE → vulnerability name helpers ─────────────────────────────────────────

# Well-known CVE IDs → CyberBattleSim-style vulnerability names
KNOWN_CVE_NAMES: Dict[str, Tuple[str, str]] = {
    "CVE-2021-44228": ("Solvability.Log4Shell",          "Log4Shell RCE via JNDI LDAP callback (CVE-2021-44228)"),
    "CVE-2021-45046": ("Solvability.Log4Shell_Bypass",   "Log4Shell incomplete fix bypass (CVE-2021-45046)"),
    "CVE-2017-0144":  ("Solvability.EternalBlue_SMB",    "EternalBlue SMB RCE via MS17-010 (CVE-2017-0144)"),
    "CVE-2019-0708":  ("Solvability.BlueKeep_RDP",       "BlueKeep pre-auth RDP RCE (CVE-2019-0708)"),
    "CVE-2020-0796":  ("Solvability.SMBGhost",           "SMBGhost unauthenticated RCE via SMBv3 (CVE-2020-0796)"),
    "CVE-2021-34527": ("Solvability.PrintNightmare",     "PrintNightmare local privilege escalation (CVE-2021-34527)"),
    "CVE-2021-36942": ("Solvability.PetitPotam",         "PetitPotam NTLM relay to AD CS (CVE-2021-36942)"),
    "CVE-2022-26134": ("Solvability.Confluence_RCE",     "Confluence OGNL injection RCE (CVE-2022-26134)"),
    "CVE-2014-6271":  ("Solvability.Shellshock_CGI",     "Shellshock CGI RCE via bash env variable (CVE-2014-6271)"),
    "CVE-2021-26855": ("Solvability.ProxyLogon",         "ProxyLogon Exchange Server SSRF+RCE (CVE-2021-26855)"),
    "CVE-2022-22965": ("Solvability.SpringShell",        "Spring Framework RCE via DataBinder (CVE-2022-22965)"),
    "CVE-2022-41082": ("Solvability.ProxyNotShell",      "ProxyNotShell Exchange SSRF+RCE (CVE-2022-41082)"),
    "CVE-2023-44487": ("Solvability.HTTP2_RapidReset",   "HTTP/2 Rapid Reset DoS (CVE-2023-44487)"),
    "CVE-2023-23397": ("Solvability.Outlook_NTLM",       "Outlook zero-click NTLM credential relay (CVE-2023-23397)"),
    "CVE-2024-3400":  ("Solvability.PanOS_RCE",          "PAN-OS command injection RCE (CVE-2024-3400)"),
}


def _cve_to_vuln_name(cve_id: str, pkg_name: str, attack_vector: str) -> str:
    """Generate a CyberBattleSim-style vulnerability name from CVE data."""
    if cve_id in KNOWN_CVE_NAMES:
        return KNOWN_CVE_NAMES[cve_id][0]
    # Derive a name from package + vector
    clean_pkg = re.sub(r"[^a-zA-Z0-9]", "_", pkg_name).strip("_").title()
    vtype = "Remote" if attack_vector == "NETWORK" else "Local"
    return f"Solvability.{clean_pkg}_{vtype}_CVE_{cve_id[-4:]}"


def _cve_to_description(cve: dict) -> str:
    """Return a description string for a CVE dict."""
    if cve["cve_id"] in KNOWN_CVE_NAMES:
        return KNOWN_CVE_NAMES[cve["cve_id"]][1]
    desc = cve.get("description", "")
    if desc:
        return desc[:200]
    return (f"{cve['severity']} vulnerability in {cve['pkg_name']} "
            f"({cve['cve_id']}) — CVSS {cve['cvss_score']:.1f}")


# ── Core prompt builder ───────────────────────────────────────────────────────

def build_config_prompt(
    scan_data:    dict,
    analysis:     dict,
    description:  str,
    config_name:  str = "repo_scenario",
) -> str:
    """
    Combine Trivy scan + repo analysis + user description into a rich prompt
    for generate_template_yaml.

    Returns a string ready to be passed as `scenario_description`.
    """
    sections: List[str] = []

    # 1. User intent
    sections.append(f"=== SCENARIO INTENT ===\n{description.strip()}")

    # 2. Detected tech stack + suggested properties
    props = analysis.get("all_properties", [])
    tiers = analysis.get("tiers", {})
    svc_map = analysis.get("service_map", {})

    sections.append(_tech_stack_section(analysis, props, tiers))

    # 3. Real CVEs from Trivy
    cves = scan_data.get("top_cves", [])
    if cves:
        sections.append(_cve_section(cves))
    else:
        sections.append(
            "=== CVE DATA ===\n"
            "No Trivy CVEs found (repo may have no package manifests or no HIGH+ vulns).\n"
            "Use generic vulnerability templates appropriate for the detected tech stack."
        )

    # 4. Suggested attack flow
    sections.append(_attack_flow_section(tiers, svc_map))

    # 5. Suggested solvability vulnerabilities (YAML seed)
    vuln_seed = _vulnerability_seed(cves, svc_map, props)
    if vuln_seed:
        sections.append(f"=== SUGGESTED SOLVABILITY VULNERABILITIES (refine as needed) ===\n{vuln_seed}")

    # 6. Config name hint
    sections.append(f"=== CONFIG NAME ===\n{config_name}")

    sep = "\n\n" + "─" * 72 + "\n\n"
    return sep.join(sections)


# ── Section builders ──────────────────────────────────────────────────────────

def _tech_stack_section(analysis: dict, props: List[str], tiers: dict) -> str:
    lines = ["=== DETECTED TECH STACK (from repo + docker-compose) ==="]

    # Tiers
    if tiers:
        lines.append("\nNetwork tiers detected:")
        for tier, svcs in tiers.items():
            lines.append(f"  {tier}: {', '.join(svcs) or '(none)'}")

    # Docker services
    docker_svcs = analysis.get("docker_services", [])
    if docker_svcs:
        lines.append("\nDocker services:")
        for ds in docker_svcs:
            p = ", ".join(ds["properties"])
            lines.append(f"  {ds['name']} (image: {ds['image'] or '?'}) → [{p}]")

    # Subprojects
    subprojects = analysis.get("subprojects", [])
    if subprojects:
        lines.append("\nSubprojects:")
        for sp in subprojects[:10]:
            p = ", ".join(sp["properties"]) or "(none)"
            lines.append(f"  {sp['path']} ({sp['pkg_manager']}) → [{p}]")

    # Suggested properties
    lines.append(f"\nSuggested base_properties for identifiers:\n  {props}")

    lines.append(
        "\nIMPORTANT: Use ONLY these detected properties when writing node_group "
        "properties. Add standard ones (DomainJoined, Unpatched, NoLAPS, WDigest, "
        "breach_node) as needed."
    )
    return "\n".join(lines)


def _cve_section(cves: List[dict]) -> str:
    lines = [
        "=== REAL CVEs FROM TRIVY SCAN ===",
        "These are actual vulnerabilities found in the scanned repository.",
        "Map them to CyberBattleSim vulnerabilities in solvability_vulnerabilities.",
        "",
    ]

    # Separate by exploitability
    network_cves = [c for c in cves if c["attack_vector"] in ("NETWORK", "ADJACENT")]
    local_cves   = [c for c in cves if c["attack_vector"] not in ("NETWORK", "ADJACENT")]

    if network_cves:
        lines.append("REMOTE-exploitable (use as remote_access or lateral movement vulns):")
        for c in network_cves[:8]:
            lines.append(
                f"  [{c['severity']}] {c['cve_id']} — {c['pkg_name']} "
                f"CVSS={c['cvss_score']:.1f}  "
                f"→ success_rate={c['success_rate']:.2f}, cost={c['exploit_cost']:.1f}"
            )
            if c.get("description"):
                lines.append(f"    {c['description'][:150]}")

    if local_cves:
        lines.append("\nLOCAL-only (use as post-exploitation or escalation vulns):")
        for c in local_cves[:6]:
            lines.append(
                f"  [{c['severity']}] {c['cve_id']} — {c['pkg_name']} "
                f"CVSS={c['cvss_score']:.1f}"
            )

    return "\n".join(lines)


def _attack_flow_section(tiers: dict, svc_map: dict) -> str:
    lines = [
        "=== SUGGESTED ATTACK FLOW (based on detected tiers) ===",
        "Use these as attack_flow entries. Each hop should be reachable from the previous.",
        "",
    ]

    tier_order = ["WebTier", "AppTier", "WorkerTier", "DataTier", "AuthTier"]
    present = [t for t in tier_order if t in tiers]

    if len(present) >= 2:
        for i in range(len(present) - 1):
            src_tier = present[i]
            tgt_tier = present[i + 1]
            src_svcs = tiers.get(src_tier, [])
            tgt_svcs = tiers.get(tgt_tier, [])
            src_type = _tier_to_node_type(src_tier)
            tgt_type = _tier_to_node_type(tgt_tier)
            lines.append(
                f"  {src_tier} ({', '.join(src_svcs[:3])}) → {tgt_tier} ({', '.join(tgt_svcs[:3])})"
            )
            lines.append(f"    attack_flow: source_pattern={src_type!r}, targets=[{tgt_type!r}]")
    else:
        lines.append(
            "  Single-tier or undifferentiated — define at least 2 hops:\n"
            "  e.g., WebServer → DatabaseServer → DomainController"
        )

    return "\n".join(lines)


def _tier_to_node_type(tier: str) -> str:
    return {
        "WebTier":    "WebServer",
        "AppTier":    "Workstation",
        "DataTier":   "DatabaseServer",
        "AuthTier":   "DomainController",
        "WorkerTier": "WorkerNode",
    }.get(tier, "Workstation")


def _vulnerability_seed(
    cves:    List[dict],
    svc_map: Dict[str, list],
    props:   List[str],
) -> str:
    """Generate a YAML snippet for solvability_vulnerabilities as a starting point."""
    if not cves:
        return ""

    network_cves = [c for c in cves if c["attack_vector"] in ("NETWORK", "ADJACENT")]
    local_cves   = [c for c in cves if c["attack_vector"] not in ("NETWORK", "ADJACENT")]

    lines = []

    # remote_access — pick top NETWORK CVE
    if network_cves:
        c = network_cves[0]
        vname = _cve_to_vuln_name(c["cve_id"], c["pkg_name"], c["attack_vector"])
        desc  = _cve_to_description(c)
        match_props = _infer_match_properties(c["pkg_name"], c.get("target_file") or c.get("target", ""), props)
        lines += [
            "solvability_vulnerabilities:",
            "  remote_access:",
            f"    - name: {vname}",
            f"      type: REMOTE",
            f"      description: \"{desc}\"",
            f"      cost: {c['exploit_cost']:.1f}",
            f"      success_rate: {c['success_rate']:.2f}",
            f"      reward: \"RCE via {c['cve_id']} on {c['pkg_name']} — initial foothold\"",
            f"      match_properties: {match_props}",
            f"      probability: 0.75",
        ]
        if len(network_cves) > 1:
            c2 = network_cves[1]
            vname2 = _cve_to_vuln_name(c2["cve_id"], c2["pkg_name"], c2["attack_vector"])
            mp2 = _infer_match_properties(c2["pkg_name"], c2.get("target_file") or c2.get("target", ""), props)
            lines += [
                f"    - name: {vname2}",
                f"      type: REMOTE",
                f"      description: \"{_cve_to_description(c2)}\"",
                f"      cost: {c2['exploit_cost']:.1f}",
                f"      success_rate: {c2['success_rate']:.2f}",
                f"      reward: \"Foothold via {c2['cve_id']}\"",
                f"      match_properties: {mp2}",
                f"      probability: 0.60",
            ]

    # credential_leak — use a local CVE or a generic harvest
    cred_lines = ["  credential_leak:"]
    if local_cves:
        c = local_cves[0]
        vname = _cve_to_vuln_name(c["cve_id"], c["pkg_name"], "LOCAL")
        mp = _infer_match_properties(c["pkg_name"], c.get("target_file") or c.get("target", ""), props)
        cred_lines += [
            f"    - name: {vname}",
            f"      type: LOCAL",
            f"      description: \"Local privilege escalation or credential theft via {c['cve_id']}\"",
            f"      cost: {c['exploit_cost']:.1f}",
            f"      success_rate: {c['success_rate']:.2f}",
            f"      reward: \"Credentials harvested\"",
            f"      match_properties: {mp}",
            f"      probability: 0.80",
        ]
    else:
        cred_lines += [
            "    - name: Local.CredentialHarvest.ConfigFiles",
            "      type: LOCAL",
            "      description: \"Read plaintext credentials from config files on compromised host\"",
            "      cost: 0.5",
            "      success_rate: 0.85",
            "      reward: \"Credentials found in configuration files\"",
            "      match_properties: [Unpatched]",
            "      probability: 0.90",
        ]
    lines.extend(cred_lines)

    # goal_access placeholder
    lines += [
        "  goal_access:",
        "    - name: Solvability.GoalService_Compromise",
        "      type: LOCAL",
        "      description: \"Compromise the target goal service using harvested credentials\"",
        "      cost: 1.0",
        "      success_rate: 0.70",
        "      reward: \"Goal node compromised\"",
        "      match_properties: []   # set to the goal service properties",
        "      is_goal: true",
        "      probability: 0.75",
    ]

    return "\n".join(lines)


def _infer_match_properties(pkg_name: str, target_file: str, all_props: List[str]) -> str:
    """Guess match_properties from package name and target file path."""
    from repo_analyzer import packages_to_props
    guessed = packages_to_props([pkg_name.lower()])
    # Intersect with what's actually in the repo
    matched = sorted(guessed & set(all_props))
    if not matched:
        # Fall back to a generic one from the target file
        if "java" in target_file.lower() or "pom" in target_file.lower():
            matched = ["Java"]
        elif "python" in target_file.lower() or "requirements" in target_file.lower():
            matched = ["Python"]
        elif "node" in target_file.lower() or "package" in target_file.lower():
            matched = ["NodeJS"]
        else:
            matched = ["Unpatched"]
    return str(matched)


# ── Intelligence summary (for human + LLM) ───────────────────────────────────

def build_intelligence_summary(scan_data: dict, analysis: dict) -> str:
    """A concise one-page summary for display in the MCP tool response."""
    cves  = scan_data.get("top_cves", [])
    props = analysis.get("all_properties", [])
    tiers = analysis.get("tiers", {})
    lines = [
        "┌─────────────────────────────────────────────────────────────────┐",
        "  REPO INTELLIGENCE SUMMARY",
        "├─────────────────────────────────────────────────────────────────┤",
        f"  CVEs found    : {scan_data.get('cve_count', 0)}  "
        f"(Critical={scan_data.get('critical', 0)}, High={scan_data.get('high', 0)}, "
        f"Network-exploitable={scan_data.get('network_exploitable', 0)})",
        f"  Pkg managers  : {', '.join(scan_data.get('pkg_managers', []))}",
        f"  Properties    : {', '.join(props[:15])}{'...' if len(props) > 15 else ''}",
        f"  Tiers         : {', '.join(tiers.keys())}",
        "├─────────────────────────────────────────────────────────────────┤",
        "  TOP CVEs:",
    ]
    for c in cves[:5]:
        lines.append(
            f"  [{c['severity']:<8}] {c['cve_id']}  {c['pkg_name']}  "
            f"CVSS={c['cvss_score']:.1f}  AV={c['attack_vector']}"
        )
    lines.append("└─────────────────────────────────────────────────────────────────┘")
    return "\n".join(lines)


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Build a CyberBattleSim config prompt from Trivy + repo analysis"
    )
    parser.add_argument("--scan",        required=True, help="Path to trivy_scanner.py JSON output")
    parser.add_argument("--analysis",    required=True, help="Path to repo_analyzer.py JSON output")
    parser.add_argument("--description", required=True, help="Scenario description")
    parser.add_argument("--name",        default="repo_scenario", help="Config name")
    parser.add_argument("--out",         default="", help="Save prompt to file (default: stdout)")
    args = parser.parse_args()

    scan_data = json.loads(Path(args.scan).read_text())
    analysis  = json.loads(Path(args.analysis).read_text())
    prompt    = build_config_prompt(scan_data, analysis, args.description, args.name)

    print(build_intelligence_summary(scan_data, analysis))
    print()

    if args.out:
        Path(args.out).write_text(prompt)
        print(f"Prompt saved to {args.out}")
    else:
        print(prompt)
